import { IImage } from "../dto";

export const IMAGES: IImage[] = [
  { id: "blurry", alt: "Image 1", isHorizontal: true },
  { id: "coffee", alt: "Image 2", isHorizontal: true },
  { id: "foggy", alt: "Image 3", isHorizontal: true },
  { id: "phone", alt: "Image 3", isHorizontal: true },
  { id: "liisi", alt: "Image 3", isHorizontal: true },
  { id: "maarja", alt: "Image 3", isHorizontal: true },
  { id: "pink", alt: "Image 3", isHorizontal: true },
  { id: "pintsak", alt: "Image 3", isHorizontal: true },
  { id: "kardin", alt: "Image 3", isHorizontal: true },
  { id: "boyband", alt: "Image 3", isHorizontal: true },
  { id: "mic", alt: "Image 3", isHorizontal: true },
  { id: "kampsun", alt: "Image 3", isHorizontal: true },
  { id: "brown", alt: "Image 3", isHorizontal: true },
  { id: "kana", alt: "Image 3", isHorizontal: true },
  { id: "suled", alt: "Image 3", isHorizontal: true },
  { id: "white", alt: "Image 3", isHorizontal: true },
  { id: "piret1", alt: "Image 3", isHorizontal: false },
  { id: "piret2", alt: "Image 3", isHorizontal: false },
  { id: "seelik", alt: "Image 3", isHorizontal: false },
  { id: "binokkel", alt: "Image 3", isHorizontal: false },
  { id: "kasukas", alt: "Image 3", isHorizontal: false },
  { id: "kleit", alt: "Image 3", isHorizontal: false },
];
